// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigSource is an autogenerated mock type for the ConfigSource type
type ConfigSource struct {
	mock.Mock
}

// Scan provides a mock function with given fields: p
func (_m *ConfigSource) Scan(p interface{}) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfigSource creates a new instance of ConfigSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigSource {
	mock := &ConfigSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
