// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	config "github.com/242617/core/config"
	mock "github.com/stretchr/testify/mock"

	source "github.com/242617/core/config/source"
)

// ConfigEngine is an autogenerated mock type for the ConfigEngine type
type ConfigEngine struct {
	mock.Mock
}

// Scan provides a mock function with given fields: _a0
func (_m *ConfigEngine) Scan(_a0 interface{}) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// With provides a mock function with given fields: _a0
func (_m *ConfigEngine) With(_a0 ...source.ConfigSource) config.ConfigEngine {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 config.ConfigEngine
	if rf, ok := ret.Get(0).(func(...source.ConfigSource) config.ConfigEngine); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ConfigEngine)
		}
	}

	return r0
}

// NewConfigEngine creates a new instance of ConfigEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigEngine {
	mock := &ConfigEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
