// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	kgo "github.com/twmb/franz-go/pkg/kgo"
)

// KafkaProducer is an autogenerated mock type for the KafkaProducer type
type KafkaProducer struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *KafkaProducer) Close() {
	_m.Called()
}

// Produce provides a mock function with given fields: ctx, r, ack
func (_m *KafkaProducer) Produce(ctx context.Context, r *kgo.Record, ack func(*kgo.Record, error)) {
	_m.Called(ctx, r, ack)
}

// ProduceSync provides a mock function with given fields: ctx, rs
func (_m *KafkaProducer) ProduceSync(ctx context.Context, rs ...*kgo.Record) kgo.ProduceResults {
	_va := make([]interface{}, len(rs))
	for _i := range rs {
		_va[_i] = rs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ProduceSync")
	}

	var r0 kgo.ProduceResults
	if rf, ok := ret.Get(0).(func(context.Context, ...*kgo.Record) kgo.ProduceResults); ok {
		r0 = rf(ctx, rs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kgo.ProduceResults)
		}
	}

	return r0
}

// NewKafkaProducer creates a new instance of KafkaProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaProducer {
	mock := &KafkaProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
