// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	pipeline "github.com/242617/core/pipeline"
	mock "github.com/stretchr/testify/mock"
)

// option is an autogenerated mock type for the option type
type option struct {
	mock.Mock
}

// Execute provides a mock function with given fields: p
func (_m *option) Execute(p *pipeline.Pipeline) {
	_m.Called(p)
}

// newOption creates a new instance of option. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *option {
	mock := &option{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
